modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "fastjson4yacl"
displayName = "FASTJSON2 Serializer for YACL"
version = "${version}"
displayURL = ""
logoFile = "assets/aiutd/icon.jpg"
authors = "VesMaybeVesper"
description = '''A config serializer for YetAnotherConfigLib using FASTJSON2'''

[[mixins]]
config = "fastjson4yacl.mixins.json"

[[dependencies.fastjson4yacl]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fastjson4yacl]]
modId = "yet_another_config_lib_v3"
mandatory = true
versionRange = "[3.7.1,)"
ordering = "NONE"
side = "BOTH"